language: python
cache: pip
os:
    - linux
services:
  - postgresql
addons:
  postgresql: "13"
dist: focal
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

matrix:
  include:
    - { python: 3.8, env: TOXENV=flake8 }
    - { python: 3.8, env: TOXENV=pydocstyle }
    - { python: 3.8, env: TOXENV=cov }
    - { python: 3.8, env: TOXENV=integration }
    # disabled temporarily due to upstream bug
    # https://github.com/celery/sphinx_celery/issues/9
    # - { python: 3.8, env: TOXENV=apicheck }
    # - { python: 3.8, env: TOXENV=linkcheck }


install: travis_retry pip install -U tox-travis
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
